name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

jobs:
  render-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: 21.x

      - name: Install Deps
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$DEPLOY_URL"
